# vim: syntax=asm-mycpu
# prismban - compressed Wire Wrap Odyssey boot banner (<=448 B, boot-sector fit).
# Generated by gen.py -- do not hand-edit; edit the generator.
#
# SELF-CONTAINED: no CALL/JMP outside this file's own code, no BIOS
# symbols, no heap, no VARs.  The only control transfer in/out is the
# entry (caller CALLs the first byte) and the final RET.  memfill/memcpy
# are the local .fill/.copy helpers below.
#
# Boot-sequence contract -- the caller does setup and teardown:
#   * the screen is already cleared when we are entered
#   * we only paint the framebuffer: glyph plane 0x4000, colour 0x5000
#   * cursor positioning / re-init is the caller's job after we RET
#   * registers are ours to trash; nothing is passed in or out
#
# Table layout (bytes): .glut 4  .wpat 6  .roys 7  .gmap 192.
# Every framebuffer cell in fb rows 0..11 is written, so no clear needed.

:main
# ---- colour plane -> 0x5000 ----------------------------------------
# Heading rows 0-2: paint the whole span magenta first (that colours the
# chrome wedges at cols 0-4 / 59-63), then repaint the middle cols 5-58
# white (row 0) / cyan (rows 1-2).  fb rows 3 and 11 are never written
# here -- every glyph there is a space, so their colour bytes don't show.
LDI_C 0x5000
LDI_AH 0x33
LDI_AL 0xbf
CALL .fill                             # fb rows 0-2 = magenta
LDI_C 0x5005
LDI_AH 0x3f
LDI_AL 0x35
CALL .fill                             # fb row 0 cols 5-58 = white
LDI_C 0x5045
LDI_AH 0x0f
LDI_AL 0x35
CALL .fill                             # fb row 1 cols 5-58 = cyan
LDI_C 0x5085
LDI_AL 0x35
CALL .fill                             # fb row 2 cols 5-58 = cyan (AH kept)
# fb row 4 colour band: seven 7-wide ROYGBIV runs, 1-col gaps left clear.
# Starts at col 5 (0x5105) to match LEFT2 -- keep in sync with gen.py.
LDI_C 0x5105
LDI_D .roys
LDI_BH 0x07
.cbld
LDA_D_AH
INCR_D
LDI_AL 0x06
CALL .fill                             # 7 cells of this letter's colour
INCR_C                                 # step over the 1-col gap
ALUOP_BH %B-1%+%BH%
JNZ .cbld
LDI_C 0x5100
LDI_D 0x5140
LDI_AL 0xff
CALL .copy                            # replicate 256 B (fb rows 5-8)
LDI_AL 0x7f
CALL .copy                            # replicate 128 B (fb rows 9-10)

# ---- glyph plane -> 0x4000 ---------------------------------------
LDI_C 0x4000
LDI_D .gmap
.p1lp
LDA_D_AH                               # AH = four packed 2-bit codes
INCR_D
CALL .cell                           # expands them to [C]..[C+3]
MOV_CH_AL
LDI_BL 0x43
ALUOP_FLAGS %A-B%+%AL%+%BL%            # C past the last fb row?
JNE .p1lp

# ---- heading chrome wedges: shade glyphs ------------------------
LDI_D 0x4001                           # fb row 0, col 1
LDI_BH 0x03                            # three heading rows
.wgrw
LDI_C .wpat
MEMCPY_C_D
MEMCPY_C_D
MEMCPY_C_D                             # cols 1-3  <- b0 b1 b2
INCR8_D
INCR8_D
INCR8_D
INCR8_D
INCR8_D
INCR8_D
INCR8_D                               # D: col 4 -> col 60
MEMCPY_C_D
MEMCPY_C_D
MEMCPY_C_D                             # cols 60-62 <- b2 b1 b0
INCR_D
INCR_D                                 # D -> next row, col 1
ALUOP_BH %B-1%+%BH%                    # row countdown (B-side decrement)
JNZ .wgrw

RET

# ---- .cell: unpack AH (four 2-bit codes) to four glyphs at [C] ----
.cell
LDI_BL 0x03
ALUOP_AL %A&B%+%AH%+%BL%               # AL = code
ALUOP_AH %A>>1%+%AH%
ALUOP_AH %A>>1%+%AH%                   # shift next code down
ALUOP_PUSH %A%+%AH%                    # stash remaining codes
LDI_AH 0x00
LDI_B .glut
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
LDA_B_AL                               # AL = glut[code]  (16-bit index, page-safe)
POP_AH                                 # restore remaining codes
ALUOP_ADDR_C %A%+%AL%                  # store glyph
INCR_C
MOV_CL_AL
LDI_BL 0x03
ALUOP_FLAGS %A&B%+%AL%+%BL%            # back to a 4-cell boundary?
JNZ .cell
RET

# ---- .fill: [C..C+AL] <- AH, one byte at a time.  On return C is one
#      past the last byte written; AH, B and D are unchanged (DL is
#      saved/restored), AL is consumed.  This is :memfill's inner loop.
.fill
PUSH_DL
ALUOP_DL %A%+%AH%                      # fill byte -> DL (faster to loop on)
.fill_loop
STA_C_DL
INCR_C
ALUOP_AL %A-1%+%AL%
JNO .fill_loop
POP_DL
RET

# ---- .copy: [C..] -> [D..] for AL+1 bytes, one byte at a time.  C and
#      D are left one past the range; AL is consumed; TD is clobbered.
#      Ascending byte order, so a self-overlapping range acts as a
#      pattern replicate.  This is :memcpy's inner loop.
.copy
MEMCPY_C_D
ALUOP_AL %A-1%+%AL%
JNO .copy
RET

.glut 0x20 0xdc 0xdf 0xdb
.wpat 0xb0 0xb1 0xb2 0xb2 0xb1 0xb0
.roys 0x30 0x38 0x3c 0x0c 0x03 0x12 0x23
.gmap 0xfc 0xc3 0xc0 0xb8 0xac 0xc6 0xaa 0x00 0x30 0x30 0xab 0x91 0x1a 0xab 0xc1 0x3f 0xfc 0xc3 0xc4 0x30 0x5c 0xc9 0x15 0x00 0x30 0x31 0x57 0x72 0x35 0x57 0xc2 0x3f 0xfc 0x83 0xb3 0x74 0x8c 0xc5 0x55 0x00 0xe0 0x2c 0x63 0x31 0x30 0x03 0xc0 0x3f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xd0 0x1f 0xfc 0x1f 0x3c 0xf0 0xf4 0x7f 0xf4 0x7f 0xfc 0xff 0x3c 0xf0 0x00 0x00 0x3c 0xf0 0x3c 0xf0 0x78 0xb4 0x3c 0x00 0x3c 0x00 0x3c 0x00 0x78 0xb4 0x00 0x00 0x3c 0xf0 0x3c 0xf0 0xe0 0x2d 0x3c 0x00 0x3c 0x00 0x3c 0x00 0xe0 0x2d 0x00 0x00 0x3c 0xf0 0x3c 0xf0 0xc0 0x0f 0xf0 0x3f 0xf0 0x3f 0xfc 0x3f 0xc0 0x0f 0x00 0x00 0x3c 0xf0 0x3c 0xf0 0xc0 0x0f 0x00 0xf0 0x00 0xf0 0x3c 0x00 0xc0 0x0f 0x00 0x00 0x3c 0xf0 0x3c 0xf0 0xc0 0x0f 0x00 0xf0 0x00 0xf0 0x3c 0x00 0xc0 0x0f 0x00 0x00 0xe0 0x2f 0xfc 0x2f 0xc0 0x0f 0xf8 0xbf 0xf8 0xbf 0xfc 0xff 0xc0 0x0f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
