"""
Extra export targets: raw split-plane binary, a C header, and an ASM data file.

All three start from `Document.composite()` -- the two 3840-byte planes the
Odyssey blits to VRAM (char plane 0x4000, color plane 0x5000, row-major
``off = row*width + col``).  The CURSOR bit (0x40) is an editor artifact and is
masked out of the color plane by default; BLINK (0x80) is kept.

  * `export_binary`   -> bytes.  ``layout="split"`` writes the whole char plane
                        then the whole color plane (default); ``"interleaved"``
                        writes ``char, color`` per cell.
  * `export_c_header` -> str.  ``<NAME>_chr[]`` / ``<NAME>_clr[]`` ``uint8_t``
                        arrays plus ``<NAME>_W`` / ``<NAME>_H`` defines, in the
                        style of the repo's ``banners.h``.
  * `export_asm`      -> str.  ``:<name>_chr`` / ``:<name>_clr`` data labels for
                        this repo's assembler (label followed by ``0xNN`` byte
                        literals; one line per plane).
"""

import re

from studio.model.palette import CURSOR_BIT

_CURSOR_MASK = (~CURSOR_BIT) & 0xFF

# Fixed-size plane formats cannot omit a cell, so "transparent" collapses to
# "null" (leave 0x00) here.
_NULL_CHAR = {"null": 0x00, "transparent": 0x00, "space": 0x20, "block": 0xDB}


def _planes(doc, mask_cursor=True, null_mode="null"):
    char_plane, color_plane = doc.composite()
    fill = _NULL_CHAR.get(null_mode, 0x00)
    if fill:
        char_plane = bytes(fill if b == 0x00 else b for b in char_plane)
    if mask_cursor:
        color_plane = bytes(b & _CURSOR_MASK for b in color_plane)
    return char_plane, color_plane


def export_binary(doc, *, layout="split", mask_cursor=True, null_mode="null") -> bytes:
    char_plane, color_plane = _planes(doc, mask_cursor, null_mode)
    if layout == "interleaved":
        out = bytearray(len(char_plane) * 2)
        out[0::2] = char_plane
        out[1::2] = color_plane
        return bytes(out)
    if layout != "split":
        raise ValueError(f"unknown layout {layout!r} (want 'split' or 'interleaved')")
    return char_plane + color_plane


def _c_ident(name: str) -> str:
    ident = re.sub(r"\W", "_", name.strip()) or "screen"
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def _byte_rows(data, per_row, fmt):
    for i in range(0, len(data), per_row):
        yield ", ".join(fmt(b) for b in data[i:i + per_row])


def export_c_header(doc, name="screen", *, mask_cursor=True, guard=True,
                    null_mode="null") -> str:
    ident = _c_ident(name)
    up = ident.upper()
    char_plane, color_plane = _planes(doc, mask_cursor, null_mode)
    w, h = doc.width, doc.height

    lines = ["/* Generated by Odyssey ANSI Studio. */", ""]
    if guard:
        lines += [f"#ifndef {up}_H", f"#define {up}_H", ""]
    lines += [
        f"#define {up}_W {w}",
        f"#define {up}_H {h}",
        f"#define {up}_CELLS {w * h}",
        "",
        f"static const unsigned char {ident}_chr[{w * h}] = {{",
    ]
    lines += ["    " + row + "," for row in _byte_rows(char_plane, w, lambda b: f"0x{b:02X}")]
    lines += ["};", "", f"static const unsigned char {ident}_clr[{w * h}] = {{"]
    lines += ["    " + row + "," for row in _byte_rows(color_plane, w, lambda b: f"0x{b:02X}")]
    lines += ["};", ""]
    if guard:
        lines += [f"#endif /* {up}_H */", ""]
    return "\n".join(lines)


def _asm_label(name: str) -> str:
    # `_chr` / `_clr` is always appended, so the labelname is always >= the
    # assembler's 4-char minimum; just sanitise and guarantee non-empty.
    return re.sub(r"[^0-9A-Za-z_]", "_", name.strip()) or "screen"


def export_asm(doc, name="screen", *, mask_cursor=True, null_mode="null") -> str:
    ident = _asm_label(name)
    char_plane, color_plane = _planes(doc, mask_cursor, null_mode)
    w, h = doc.width, doc.height
    chr_bytes = " ".join(f"0x{b:02x}" for b in char_plane)
    clr_bytes = " ".join(f"0x{b:02x}" for b in color_plane)
    return "\n".join([
        "# Generated by Odyssey ANSI Studio.",
        f"# {w}x{h} cells, row-major (off = row*{w} + col).",
        "# Char plane loads at 0x4000, color plane at 0x5000.",
        "",
        f":{ident}_chr {chr_bytes}",
        f":{ident}_clr {clr_bytes}",
        "",
    ])
