# system/Makefile - SYSTEM.ODY build

include ../config.mk

#------------------------------------------------------------------------------
# Configuration
#------------------------------------------------------------------------------
FILENAME := SYSTEM.ODY
INSTALL_SUBDIR :=  # Install to root of SD card

include ../rules.mk

