# system/Makefile - SYSTEM.ODY build

include ../config.mk

#------------------------------------------------------------------------------
# Configuration
#------------------------------------------------------------------------------
FILENAME := SYSTEM.ODY
# Install to root of SD card
INSTALL_SUBDIR :=

include ../rules.mk

