VAR global byte $ring_read_page
VAR global byte $ring_write_page
VAR global byte $frames_in_buffer
VAR global word $total_frames_remaining
VAR global word $frame_count
VAR global word $playback_frame
VAR global byte $isr_saved_e_page
VAR global byte $frame_segments
VAR global byte $color_mode
