# vim: syntax=asm-mycpu

# C compiler helper functions
#
# These are shared subroutines called by code generated by the C compiler
# (c_compiler/codegen.py). They replace repeated inline patterns for
# local variable access, reducing compiled binary sizes.
#
# The D register is the frame pointer for the current C function's stack frame.
# Local variables are at positive offsets from D; parameters at negative offsets.

########################################################################
# Group 1: Rvalue loaders
#
# Load the value of a frame-relative variable into a register.
# These replace the inline pattern: save other_reg, MOV D to other_reg,
# add offset via INCR/DECR or ALUOP16O, deref load, restore other_reg.
########################################################################

######
# Load 16-bit rvalue into A from frame-relative address D+offset.
# Positive offset (local variables).
#
# Call: LDI_AL <offset>    (unsigned byte 1-255)
#       CALL :__cc_rval16p_A
# Result: AH:AL = 16-bit value at [D+offset]
# Preserves: B, D
:__cc_rval16p_A
ALUOP_PUSH %B%+%BL%
ALUOP_PUSH %B%+%BH%
LDI_AH 0x00
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
LDA_B_AH
ALUOP16O_B %B+1%+%BL% %B+1%+%BH% %B%+%BH%
LDA_B_AL
POP_BH
POP_BL
RET

######
# Load 16-bit rvalue into B from frame-relative address D+offset.
# Positive offset (local variables).
#
# Call: LDI_BL <offset>    (unsigned byte 1-255)
#       CALL :__cc_rval16p_B
# Result: BH:BL = 16-bit value at [D+offset]
# Preserves: A, D
:__cc_rval16p_B
ALUOP_PUSH %A%+%AL%
ALUOP_PUSH %A%+%AH%
LDI_BH 0x00
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
LDA_A_BH
ALUOP16O_A %A+1%+%AL% %A+1%+%AH% %A%+%AH%
LDA_A_BL
POP_AH
POP_AL
RET

######
# Load 8-bit rvalue into AL from frame-relative address D+offset.
# Positive offset (local variables).
#
# Call: LDI_AL <offset>    (unsigned byte 1-255)
#       CALL :__cc_rval8p_AL
# Result: AL = 8-bit value at [D+offset]
# Preserves: AH, B, D
:__cc_rval8p_AL
ALUOP_PUSH %B%+%BL%
ALUOP_PUSH %B%+%BH%
ALUOP_PUSH %A%+%AH%
LDI_AH 0x00
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_AH
LDA_B_AL
POP_BH
POP_BL
RET

######
# Load 8-bit rvalue into BL from frame-relative address D+offset.
# Positive offset (local variables).
#
# Call: LDI_BL <offset>    (unsigned byte 1-255)
#       CALL :__cc_rval8p_BL
# Result: BL = 8-bit value at [D+offset]
# Preserves: A, BH, D
:__cc_rval8p_BL
ALUOP_PUSH %A%+%AL%
ALUOP_PUSH %A%+%AH%
ALUOP_PUSH %B%+%BH%
LDI_BH 0x00
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_BH
LDA_A_BL
POP_AH
POP_AL
RET

######
# Load 16-bit rvalue into A from frame-relative address D+offset.
# Negative/signed offset (function parameters).
#
# Call: LDI_A <offset>     (signed 16-bit, e.g. 0xfffd for -3)
#       CALL :__cc_rval16n_A
# Result: AH:AL = 16-bit value at [D+offset]
# Preserves: B, D
:__cc_rval16n_A
ALUOP_PUSH %B%+%BL%
ALUOP_PUSH %B%+%BH%
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
LDA_B_AH
ALUOP16O_B %B+1%+%BL% %B+1%+%BH% %B%+%BH%
LDA_B_AL
POP_BH
POP_BL
RET

######
# Load 16-bit rvalue into B from frame-relative address D+offset.
# Negative/signed offset (function parameters).
#
# Call: LDI_B <offset>     (signed 16-bit, e.g. 0xfffd for -3)
#       CALL :__cc_rval16n_B
# Result: BH:BL = 16-bit value at [D+offset]
# Preserves: A, D
:__cc_rval16n_B
ALUOP_PUSH %A%+%AL%
ALUOP_PUSH %A%+%AH%
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
LDA_A_BH
ALUOP16O_A %A+1%+%AL% %A+1%+%AH% %A%+%AH%
LDA_A_BL
POP_AH
POP_AL
RET

######
# Load 8-bit rvalue into AL from frame-relative address D+offset.
# Negative/signed offset (function parameters).
#
# Call: LDI_A <offset>     (signed 16-bit, e.g. 0xffff for -1)
#       CALL :__cc_rval8n_AL
# Result: AL = 8-bit value at [D+offset]
# Preserves: AH, B, D
:__cc_rval8n_AL
ALUOP_PUSH %B%+%BL%
ALUOP_PUSH %B%+%BH%
ALUOP_PUSH %A%+%AH%
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_AH
LDA_B_AL
POP_BH
POP_BL
RET

######
# Load 8-bit rvalue into BL from frame-relative address D+offset.
# Negative/signed offset (function parameters).
#
# Call: LDI_B <offset>     (signed 16-bit, e.g. 0xffff for -1)
#       CALL :__cc_rval8n_BL
# Result: BL = 8-bit value at [D+offset]
# Preserves: A, BH, D
:__cc_rval8n_BL
ALUOP_PUSH %A%+%AL%
ALUOP_PUSH %A%+%AH%
ALUOP_PUSH %B%+%BH%
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_BH
LDA_A_BL
POP_AH
POP_AL
RET

########################################################################
# Group 2: Lvalue address loaders
#
# Compute the address D+offset into a register, for use as an lvalue
# (store target). Only used for large offsets (>= 10) where inline
# INCR/DECR sequences would be longer.
########################################################################

######
# Compute address D+offset into B. Positive offset, passed in AL.
#
# Call: LDI_AL <offset>    (unsigned byte 10-255)
#       CALL :__cc_lval_p_B
# Result: BH:BL = D + offset
# Preserves: AL, D
# Side effects: Clobbers AH (saved/restored internally)
:__cc_lval_p_B
ALUOP_PUSH %A%+%AH%
LDI_AH 0x00
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_AH
RET

######
# Compute address D+offset into A. Positive offset, passed in BL.
#
# Call: LDI_BL <offset>    (unsigned byte 10-255)
#       CALL :__cc_lval_p_A
# Result: AH:AL = D + offset
# Preserves: BL, D
# Side effects: Clobbers BH (saved/restored internally)
:__cc_lval_p_A
ALUOP_PUSH %B%+%BH%
LDI_BH 0x00
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_BH
RET

######
# Compute address D+offset into B. Signed offset in AH:AL.
#
# Call: LDI_A <offset>     (signed 16-bit)
#       CALL :__cc_lval_n_B
# Result: BH:BL = D + offset
# Preserves: D
# Side effects: Clobbers A (caller must save if needed)
:__cc_lval_n_B
MOV_DH_BH
MOV_DL_BL
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
RET

######
# Compute address D+offset into A. Signed offset in BH:BL.
#
# Call: LDI_B <offset>     (signed 16-bit)
#       CALL :__cc_lval_n_A
# Result: AH:AL = D + offset
# Preserves: D
# Side effects: Clobbers B (caller must save if needed)
:__cc_lval_n_A
MOV_DH_AH
MOV_DL_AL
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
RET

########################################################################
# Group 3: 16-bit store helpers
#
# Store a 16-bit value to an address (big-endian byte order).
# Replaces 4-instruction inline store sequence.
########################################################################

######
# Store AH:AL to the address in B (big-endian).
#
# Call: CALL :__cc_store16_AB
# Stores: AH at [B], AL at [B+1]
# Preserves: A, D
# Side effects: B is left pointing at [B+1], then restored to [B]
:__cc_store16_AB
ALUOP_ADDR_B %A%+%AH%
ALUOP16O_B %B+1%+%BL% %B+1%+%BH% %B%+%BH%
ALUOP_ADDR_B %A%+%AL%
ALUOP16O_B %B-1%+%BL% %B-1%+%BH% %B%+%BH%
RET

######
# Store BH:BL to the address in A (big-endian).
#
# Call: CALL :__cc_store16_BA
# Stores: BH at [A], BL at [A+1]
# Preserves: B, D
# Side effects: A is left pointing at [A+1], then restored to [A]
:__cc_store16_BA
ALUOP_ADDR_A %B%+%BH%
ALUOP16O_A %A+1%+%AL% %A+1%+%AH% %A%+%AH%
ALUOP_ADDR_A %B%+%BL%
ALUOP16O_A %A-1%+%AL% %A-1%+%AH% %A%+%AH%
RET

########################################################################
# Group 4: Struct member offset helpers
#
# Add a struct member offset to a base address register.
# Used when the offset is 3-255 bytes and -Os is active.
########################################################################

######
# Add unsigned offset in AL to address in B. Saves/restores AH.
#
# Call site pattern (compiler-generated):
#   ALUOP_PUSH %A%+%AL%   # save AL (may be live)
#   LDI_AL <offset>
#   CALL :__cc_add_off_p_B
#   POP_AL                 # restore AL
# Result: BH:BL = BH:BL + offset
# Preserves: BL, D
# Side effects: AH clobbered (saved/restored internally)
:__cc_add_off_p_B
ALUOP_PUSH %A%+%AH%
LDI_AH 0x00
ALUOP16O_B %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_AH
RET

######
# Add unsigned offset in BL to address in A. Saves/restores BH.
#
# Call site pattern (compiler-generated):
#   ALUOP_PUSH %B%+%BL%   # save BL (may be live)
#   LDI_BL <offset>
#   CALL :__cc_add_off_p_A
#   POP_BL                 # restore BL
# Result: AH:AL = AH:AL + offset
# Preserves: AL, D
# Side effects: BH clobbered (saved/restored internally)
:__cc_add_off_p_A
ALUOP_PUSH %B%+%BH%
LDI_BH 0x00
ALUOP16O_A %A+B%+%AL%+%BL% %A+B%+%AH%+%BH%+%Cin% %A+B%+%AH%+%BH%
POP_BH
RET
